#!/usr/bin/env bash
set -euo pipefail

if [[ "${EUID}" -ne 0 ]]; then
  echo "Run as root (sudo)." >&2
  exit 1
fi

CERT_PATH="${CERT_PATH:-}"
KEY_PATH="${KEY_PATH:-}"
ALLOW_ALL_PORTS="${ALLOW_ALL_PORTS:-0}"
ALLOWED_PORTS="${ALLOWED_PORTS:-8443}"
REMOVE_DEFAULT_SITE="${REMOVE_DEFAULT_SITE:-0}"
AUTO_FIX_PROJECT="${AUTO_FIX_PROJECT:-1}"
CONF_PATH="/etc/nginx/conf.d/celerity-vless-path-proxy.conf"
PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"

if [[ -z "${CERT_PATH}" || -z "${KEY_PATH}" ]]; then
  cat >&2 <<'EOF'
CERT_PATH and KEY_PATH are required.
Example:
  sudo CERT_PATH=/etc/letsencrypt/live/example.com/fullchain.pem \
       KEY_PATH=/etc/letsencrypt/live/example.com/privkey.pem \
       bash /path/to/scripts/install-nginx-vless-path-proxy.sh
EOF
  exit 1
fi

if [[ ! -f "${CERT_PATH}" || ! -f "${KEY_PATH}" ]]; then
  echo "Certificate files not found: CERT_PATH=${CERT_PATH}, KEY_PATH=${KEY_PATH}" >&2
  exit 1
fi

install_nginx() {
  if command -v nginx >/dev/null 2>&1; then
    return
  fi

  if command -v apt-get >/dev/null 2>&1; then
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -y
    apt-get install -y nginx
  elif command -v dnf >/dev/null 2>&1; then
    dnf install -y nginx
  elif command -v yum >/dev/null 2>&1; then
    yum install -y epel-release || true
    yum install -y nginx
  else
    echo "Unsupported package manager. Install nginx manually and re-run." >&2
    exit 1
  fi
}

disable_conflicting_host_services() {
  local svc
  for svc in caddy apache2 httpd; do
    if systemctl list-unit-files "${svc}.service" >/dev/null 2>&1; then
      systemctl disable --now "${svc}" >/dev/null 2>&1 || true
    fi
  done
}

set_env_key() {
  local file="$1"
  local key="$2"
  local value="$3"
  if [[ ! -f "${file}" ]]; then
    return
  fi

  if grep -qE "^${key}=" "${file}"; then
    sed -i "s#^${key}=.*#${key}=${value}#g" "${file}"
  else
    printf '\n%s=%s\n' "${key}" "${value}" >> "${file}"
  fi
}

patch_hub_compose_for_nginx() {
  local compose_file="$1"
  [[ -f "${compose_file}" ]] || return 0

  cp "${compose_file}" "${compose_file}.bak.$(date +%Y%m%d%H%M%S)"
  python3 - <<'PY' "${compose_file}"
import pathlib, re, sys
p = pathlib.Path(sys.argv[1])
text = p.read_text(encoding="utf-8")

# Replace host-exposed 80/443 with localhost 3000.
text = re.sub(
    r'^\s{4}ports:\n\s{6}- "80:80/tcp"\n\s{6}- "443:443/tcp"\n',
    '    ports:\n      - "127.0.0.1:3000:3000/tcp"\n',
    text,
    flags=re.M
)

# Remove Greenlock volume (TLS handled by host nginx).
text = re.sub(r'^\s{6}- \./greenlock\.d:/app/greenlock\.d\n', '', text, flags=re.M)

# Force backend app to run in reverse-proxy mode.
if re.search(r'^\s*USE_CADDY:\s*', text, flags=re.M):
    text = re.sub(r'^\s*USE_CADDY:\s*.*\n?', '', text, flags=re.M)

if not re.search(r'^\s*USE_NGINX:\s*', text, flags=re.M):
    text = re.sub(
        r'(\n\s{6}REDIS_URL:[^\n]*\n)',
        r'\1      USE_NGINX: "true"\n',
        text
    )
if not re.search(r'^\s*PORT:\s*', text, flags=re.M):
    text = re.sub(
        r'(\n\s{6}USE_NGINX:[^\n]*\n)',
        r'\1      PORT: 3000\n',
        text
    )

p.write_text(text, encoding="utf-8")
PY
}

auto_fix_project_compat() {
  if [[ "${AUTO_FIX_PROJECT}" != "1" ]]; then
    return
  fi

  local env_file="${PROJECT_DIR}/.env"
  set_env_key "${env_file}" "USE_NGINX" "true"
  set_env_key "${env_file}" "PORT" "3000"

  patch_hub_compose_for_nginx "${PROJECT_DIR}/docker-compose.hub.yml"
}

build_ports_map() {
  local map_lines='map $target_port $celerity_port_allowed {
    default 0;'

  IFS=',' read -r -a ports <<< "${ALLOWED_PORTS}"
  for raw in "${ports[@]}"; do
    local p
    p="$(echo "${raw}" | xargs)"
    [[ -z "${p}" ]] && continue
    if [[ ! "${p}" =~ ^[0-9]+$ ]] || (( p < 1 || p > 65535 )); then
      echo "Invalid port in ALLOWED_PORTS: ${p}" >&2
      exit 1
    fi
    map_lines+=$'\n'"    ${p} 1;"
  done
  map_lines+=$'\n''}'

  printf '%s\n' "${map_lines}"
}

write_config() {
  local ports_map
  if [[ "${ALLOW_ALL_PORTS}" == "1" ]]; then
    ports_map='map $target_port $celerity_port_allowed {
    default 1;
}'
  else
    ports_map="$(build_ports_map)"
  fi

  cat > "${CONF_PATH}" <<EOF
# Generated by scripts/install-nginx-vless-path-proxy.sh
# Routes:
#   /{port}/{path...} -> 127.0.0.1:{port}/{path...}
# Supports WS/XHTTP/gRPC/HTTP-upgrade over :443 (TLS) and :80 (non-TLS).

map \$http_upgrade \$connection_upgrade {
    default upgrade;
    '' close;
}

map \$http_content_type \$celerity_is_grpc {
    default 0;
    "~*application/grpc" 1;
}

${ports_map}

server {
    listen 443 ssl http2 default_server;
    listen [::]:443 ssl http2 default_server;
    server_name _;

    ssl_certificate ${CERT_PATH};
    ssl_certificate_key ${KEY_PATH};
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;
    ssl_protocols TLSv1.2 TLSv1.3;

    # Allows CDN-origin requests regardless of Host header/domain.
    underscores_in_headers on;
    ignore_invalid_headers off;

    error_page 418 = @celerity_grpc;

    location ~ ^/(?<target_port>\d{1,5})(?<target_path>/.*)$ {
        if (\$celerity_port_allowed = 0) {
            return 403;
        }

        set \$celerity_target_port \$target_port;
        set \$celerity_target_path \$target_path;

        if (\$celerity_is_grpc = 1) {
            return 418;
        }

        rewrite ^/\d{1,5}(/.*)$ \$1 break;

        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_pass http://127.0.0.1:\$celerity_target_port;
    }

    location @celerity_grpc {
        internal;
        if (\$celerity_port_allowed = 0) {
            return 403;
        }
        rewrite ^ \$celerity_target_path break;
        grpc_set_header Host \$host;
        grpc_read_timeout 3600s;
        grpc_send_timeout 3600s;
        grpc_pass grpc://127.0.0.1:\$celerity_target_port;
    }

    location / {
        return 404;
    }
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    underscores_in_headers on;
    ignore_invalid_headers off;

    error_page 418 = @celerity_grpc_http;

    location ~ ^/(?<target_port>\d{1,5})(?<target_path>/.*)$ {
        if (\$celerity_port_allowed = 0) {
            return 403;
        }

        set \$celerity_target_port \$target_port;
        set \$celerity_target_path \$target_path;

        if (\$celerity_is_grpc = 1) {
            return 418;
        }

        rewrite ^/\d{1,5}(/.*)$ \$1 break;

        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_pass http://127.0.0.1:\$celerity_target_port;
    }

    location @celerity_grpc_http {
        internal;
        if (\$celerity_port_allowed = 0) {
            return 403;
        }
        rewrite ^ \$celerity_target_path break;
        grpc_set_header Host \$host;
        grpc_read_timeout 3600s;
        grpc_send_timeout 3600s;
        grpc_pass grpc://127.0.0.1:\$celerity_target_port;
    }

    location / {
        return 404;
    }
}
EOF
}

install_nginx
disable_conflicting_host_services
auto_fix_project_compat
write_config

if [[ "${REMOVE_DEFAULT_SITE}" == "1" ]]; then
  rm -f /etc/nginx/sites-enabled/default 2>/dev/null || true
fi
nginx -t
systemctl enable --now nginx
systemctl reload nginx

cat <<EOF
Done.
Config: ${CONF_PATH}

Current mode:
  ALLOW_ALL_PORTS=${ALLOW_ALL_PORTS}
  ALLOWED_PORTS=${ALLOWED_PORTS}
  REMOVE_DEFAULT_SITE=${REMOVE_DEFAULT_SITE}

IMPORTANT:
  - Subscription paths should look like /{internalPort}/...
  - Keep panel/admin ports out of ALLOWED_PORTS unless intentionally exposed.
  - AUTO_FIX_PROJECT=${AUTO_FIX_PROJECT} updates .env and docker-compose.hub.yml for nginx-only mode.
EOF
