#!/usr/bin/env bash
set -euo pipefail

if [[ "${EUID}" -ne 0 ]]; then
  echo "Run as root (sudo)." >&2
  exit 1
fi

CERT_PATH="${CERT_PATH:-}"
KEY_PATH="${KEY_PATH:-}"
ALLOW_ALL_PORTS="${ALLOW_ALL_PORTS:-0}"
ALLOWED_PORTS="${ALLOWED_PORTS:-443,8443}"
REMOVE_DEFAULT_SITE="${REMOVE_DEFAULT_SITE:-0}"
CONF_PATH="/etc/nginx/conf.d/celerity-vless-path-proxy.conf"

if [[ -z "${CERT_PATH}" || -z "${KEY_PATH}" ]]; then
  cat >&2 <<'EOF'
CERT_PATH and KEY_PATH are required.
Example:
  sudo CERT_PATH=/etc/letsencrypt/live/example.com/fullchain.pem \
       KEY_PATH=/etc/letsencrypt/live/example.com/privkey.pem \
       bash /path/to/scripts/install-nginx-vless-path-proxy.sh
EOF
  exit 1
fi

if [[ ! -f "${CERT_PATH}" || ! -f "${KEY_PATH}" ]]; then
  echo "Certificate files not found: CERT_PATH=${CERT_PATH}, KEY_PATH=${KEY_PATH}" >&2
  exit 1
fi

install_nginx() {
  if command -v nginx >/dev/null 2>&1; then
    return
  fi

  if command -v apt-get >/dev/null 2>&1; then
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -y
    apt-get install -y nginx
  elif command -v dnf >/dev/null 2>&1; then
    dnf install -y nginx
  elif command -v yum >/dev/null 2>&1; then
    yum install -y epel-release || true
    yum install -y nginx
  else
    echo "Unsupported package manager. Install nginx manually and re-run." >&2
    exit 1
  fi
}

build_ports_map() {
  local map_lines='map $target_port $celerity_port_allowed {
    default 0;'

  IFS=',' read -r -a ports <<< "${ALLOWED_PORTS}"
  for raw in "${ports[@]}"; do
    local p
    p="$(echo "${raw}" | xargs)"
    [[ -z "${p}" ]] && continue
    if [[ ! "${p}" =~ ^[0-9]+$ ]] || (( p < 1 || p > 65535 )); then
      echo "Invalid port in ALLOWED_PORTS: ${p}" >&2
      exit 1
    fi
    map_lines+=$'\n'"    ${p} 1;"
  done
  map_lines+=$'\n''}'

  printf '%s\n' "${map_lines}"
}

write_config() {
  local ports_map
  if [[ "${ALLOW_ALL_PORTS}" == "1" ]]; then
    ports_map='map $target_port $celerity_port_allowed {
    default 1;
}'
  else
    ports_map="$(build_ports_map)"
  fi

  cat > "${CONF_PATH}" <<EOF
# Generated by scripts/install-nginx-vless-path-proxy.sh
# Routes:
#   /{port}/{path...} -> 127.0.0.1:{port}/{path...}
# Supports WS/XHTTP and gRPC over TLS on :443 with host-agnostic server_name.

map \$http_upgrade \$connection_upgrade {
    default upgrade;
    '' close;
}

map \$http_content_type \$celerity_is_grpc {
    default 0;
    "~*application/grpc" 1;
}

${ports_map}

server {
    listen 443 ssl http2 default_server;
    listen [::]:443 ssl http2 default_server;
    server_name _;

    ssl_certificate ${CERT_PATH};
    ssl_certificate_key ${KEY_PATH};
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;
    ssl_protocols TLSv1.2 TLSv1.3;

    # Allows CDN-origin requests regardless of Host header/domain.
    underscores_in_headers on;
    ignore_invalid_headers off;

    error_page 418 = @celerity_grpc;

    location ~ ^/(?<target_port>\d{1,5})(?<target_path>/.*)$ {
        if (\$celerity_port_allowed = 0) {
            return 403;
        }

        set \$celerity_target_port \$target_port;
        set \$celerity_target_path \$target_path;

        if (\$celerity_is_grpc = 1) {
            return 418;
        }

        rewrite ^/\d{1,5}(/.*)$ \$1 break;

        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_pass http://127.0.0.1:\$celerity_target_port;
    }

    location @celerity_grpc {
        internal;
        if (\$celerity_port_allowed = 0) {
            return 403;
        }
        rewrite ^ \$celerity_target_path break;
        grpc_set_header Host \$host;
        grpc_read_timeout 3600s;
        grpc_send_timeout 3600s;
        grpc_pass grpc://127.0.0.1:\$celerity_target_port;
    }

    location / {
        return 404;
    }
}
EOF
}

install_nginx
write_config

if [[ "${REMOVE_DEFAULT_SITE}" == "1" ]]; then
  rm -f /etc/nginx/sites-enabled/default 2>/dev/null || true
fi
nginx -t
systemctl enable --now nginx
systemctl reload nginx

cat <<EOF
Done.
Config: ${CONF_PATH}

Current mode:
  ALLOW_ALL_PORTS=${ALLOW_ALL_PORTS}
  ALLOWED_PORTS=${ALLOWED_PORTS}
  REMOVE_DEFAULT_SITE=${REMOVE_DEFAULT_SITE}

IMPORTANT:
  - Subscription paths should look like /{internalPort}/...
  - Keep panel/admin ports out of ALLOWED_PORTS unless intentionally exposed.
EOF
